import React, { useMemo, useState } from 'react';
import { CheckCircle2, ChevronLeft, ChevronRight, FileCheck2, HelpCircle, Loader2, Send } from 'lucide-react';

type Answers = Record<string, string | string[] | boolean>;
type Field = { id: string; label: string; type?: 'text'|'email'|'tel'|'number'|'textarea'|'select'|'radio'|'checkboxes'; options?: string[]; why?: string; required?: boolean; show?: (a: Answers) => boolean };
type Section = { title: string; intro: string; fields: Field[] };

const why = (text: string, legal: string) => `${text}\n\nPrávny základ: ${legal}`;
const WHY = {
  identity: why('Potrebujeme jednoznačne určiť povinnú osobu a prispôsobiť jej program veľkosti, štruktúre a činnosti. Názov, sídlo alebo miesto podnikania a IČO sa používajú aj pri hlásení neobvyklej obchodnej operácie (NOO).','§ 20 ods. 1; § 17 ods. 3 písm. a) zákona č. 297/2008 Z. z.'),
  services: why('Rozsah služieb ovplyvňuje riziko: spracovanie podkladov, disponovanie účtom či manipulácia s hotovosťou vytvárajú rozdielne situácie. Údaj používame na prispôsobenie programu predmetu činnosti a určenie rizík.','§ 20 ods. 1; § 20 ods. 2 písm. a) až c); § 20a ods. 1 zákona č. 297/2008 Z. z.'),
  clientCount: why('Tento údaj používame ako podklad na určenie reálneho rozsahu činnosti a primerané nastavenie zodpovedností, kontrol a AML procesov.','§ 20 ods. 1; § 20a ods. 1 a 2 zákona č. 297/2008 Z. z.'),
  industries: why('Typ klienta a jeho podnikanie sú vstupmi do povinného hodnotenia rizík. Údaj používame ako podklad na rizikový profil klientely a primerané opatrenia. Samotné odvetvie automaticky neznamená NOO.','§ 20a ods. 1; § 10 ods. 4 a príloha č. 2 zákona č. 297/2008 Z. z.'),
  foreign: why('Geografická oblasť je súčasťou hodnotenia rizík. Pri osobách usadených vo vysokorizikových krajinách sa uplatňuje zvýšená starostlivosť; samotná zahraničná väzba nie je automaticky vysoké riziko.','§ 20a ods. 1; § 12 ods. 1 a ods. 2 písm. d) a príloha č. 2 bod 3 zákona č. 297/2008 Z. z.'),
  organization: why('Program musí zohľadňovať veľkosť a organizačnú štruktúru povinnej osoby. Údaje slúžia na primerané rozdelenie úloh, zodpovedností, kontrol a školení; mená všetkých pracovníkov na tento účel nepotrebujeme.','§ 20 ods. 1; § 20 ods. 2 písm. e), i), j), k) a § 20 ods. 3 zákona č. 297/2008 Z. z.'),
  branches: why('Pobočky a miesta výkonu činnosti vplývajú na organizačné nastavenie programu. Pri zahraničných pobočkách treba posúdiť aj osobitné pravidlá.','§ 20 ods. 1; § 20a ods. 3; § 21 ods. 4 zákona č. 297/2008 Z. z.'),
  existing: why('Povinná osoba musí mať aktuálny program a primerané hodnotenie rizík. Informácia o súčasnom alebo predchádzajúcom systéme umožní vyhodnotiť medzery a zachovať použiteľné postupy.','§ 20 ods. 1 a 2; § 20a ods. 1 a 2 zákona č. 297/2008 Z. z.'),
  identityMethod: why('Základná starostlivosť zahŕňa identifikáciu klienta a overenie jeho identifikácie. Zisťujeme dnešný postup, aby sme vedeli určiť potrebné úpravy. Samotná kópia dokladu alebo údaj v registri nemusí pokrývať celý postup.','§ 10 ods. 1 písm. a); § 7 a § 8 zákona č. 297/2008 Z. z.'),
  kuv: why('Starostlivosť zahŕňa identifikáciu konečného užívateľa výhod (KÚV) a primerané overenie zo spoľahlivých zdrojov vrátane vlastníckej a riadiacej štruktúry. Pri overovaní sa nemožno spoliehať výlučne na register právnických osôb.','§ 10 ods. 1 písm. b); § 6a zákona č. 297/2008 Z. z.'),
  pepSanctions: why('Povinná osoba zisťuje, či klient alebo KÚV je politicky exponovanou alebo sankcionovanou osobou. Pri PEP sa uplatňuje zvýšená starostlivosť; PEP ani zahraničná väzba automaticky neznamenajú podozrivého klienta alebo NOO.','§ 6; § 10 ods. 1 písm. d); § 12 ods. 1 a ods. 2 písm. c); § 20 ods. 2 písm. l) zákona č. 297/2008 Z. z.'),
  risk: why('Povinná osoba identifikuje, posudzuje a aktualizuje riziká podľa vlastnej činnosti a klientov. Zisťujeme existujúci spôsob hodnotenia; zákon nepredpisuje konkrétnu trojstupňovú škálu.','§ 20a ods. 1 a 2; § 10 ods. 4; § 20 ods. 2 písm. c) zákona č. 297/2008 Z. z.'),
  monitoring: why('Starostlivosť zahŕňa priebežné monitorovanie obchodného vzťahu, porovnávanie obchodov s profilom klienta a aktualizáciu údajov a dokumentov.','§ 10 ods. 1 písm. g); § 14 zákona č. 297/2008 Z. z.'),
  onboarding: why('Spôsob získania klienta a distribučný kanál ovplyvňujú riziko, najmä pri vzťahoch uzatváraných bez fyzickej prítomnosti klienta.','§ 20a ods. 1 a príloha č. 2 bod 2 písm. c) zákona č. 297/2008 Z. z.'),
  purpose: why('Základná starostlivosť zahŕňa získanie a vyhodnotenie účelu a plánovanej povahy obchodného vzťahu a povahy podnikania klienta. Zisťujeme, ktoré informácie sa reálne získavajú pri prijatí.','§ 10 ods. 1 písm. c) zákona č. 297/2008 Z. z.'),
  refusal: why('Ak nemožno vykonať zákonom určenú starostlivosť alebo klient odmietne preukázať, v mene koho koná, zákon upravuje odmietnutie či ukončenie obchodného vzťahu a posúdenie NOO.','§ 15 zákona č. 297/2008 Z. z.'),
  ownership: why('Zložitosť vlastníckej štruktúry je faktorom na ďalšie posúdenie, nie automatickým záverom o NOO. Údaj slúži na nastavenie spôsobu identifikácie a overovania KÚV.','§ 10 ods. 1 písm. b); § 20a ods. 1 a príloha č. 2 bod 1 písm. g) zákona č. 297/2008 Z. z.'),
  situations: why('Uvedené situácie sú faktormi, ktoré môžu vyžadovať podrobnejšie posúdenie. Ich výskyt sám osebe neznamená NOO; údaje použijeme na nastavenie rizikových indikátorov a primeraného monitorovania.','§ 20a ods. 1; § 4 a § 14 zákona č. 297/2008 Z. z.; príloha č. 2 zákona č. 297/2008 Z. z.'),
  crypto: why('Pri hodnotení rizík sa zohľadňujú aj nové produkty, postupy a technológie. Spôsob používania kryptoaktív je podkladom na posúdenie rizika; samotné používanie kryptoaktív automaticky neznamená NOO.','§ 20a ods. 1 zákona č. 297/2008 Z. z.'),
  cash: why('Intenzívne používanie hotovosti je faktorom potenciálne vyššieho rizika. Údaj používame ako podklad na profil klientely, rizikové indikátory a primeraný monitoring.','§ 20a ods. 1 a príloha č. 2 bod 1 písm. f) zákona č. 297/2008 Z. z.'),
  suspicious: why('Program má obsahovať konkrétne formy NOO relevantné pre danú činnosť. Odpoveď použijeme na nastavenie indikátorov a postupu posudzovania; okolnosť sama osebe neznamená NOO. Uvádzajte iba anonymizovaný typ situácie.','§ 20 ods. 2 písm. a) a d); § 4 a § 14 zákona č. 297/2008 Z. z.'),
  goaml: why('Od 1. júna 2026 zákon vyžaduje registráciu v informačnom systéme Policajného zboru na prijímanie a analýzu hlásení NOO. Nová povinná osoba sa registruje do 30 dní; pre osoby existujúce k 1. júnu 2026 sa uplatňuje prechodný termín 30. novembra 2026.','§ 21 ods. 2; § 36d ods. 1 zákona č. 297/2008 Z. z.'),
  payments: why('Údaj používame na posúdenie transakčných oprávnení, prístupu k informáciám a možnosti ovplyvniť operáciu. Rozlišujeme náhľad, prípravu a autorizáciu platieb.','§ 20 ods. 1; § 20a ods. 1; § 16 zákona č. 297/2008 Z. z.'),
  amlPerson: why('Pracovné zaradenie určenej AML osoby je povinnou náležitosťou programu. Ak nejde o štatutára, treba zohľadniť jej postavenie, vedomosti, rozhodovacie oprávnenia, priamu komunikáciu s orgánmi a prístup k podkladom.','§ 20 ods. 2 písm. h) zákona č. 297/2008 Z. z.'),
  systems: why('Používané systémy a spôsob uloženia údajov sú podkladom na nastavenie dostupnosti dokumentácie pre AML osobu, uchovávania záznamov a vnútornej kontroly. Program musí upravovať uchovávanie údajov a správne lehoty.','§ 19; § 20 ods. 2 písm. g) a h) zákona č. 297/2008 Z. z.'),
  inspection: why('Údaj používame na zistenie predtým vytknutých nedostatkov, spôsobu ich nápravy a otvorených úloh, ktoré treba premietnuť do nového programu.','§ 20 ods. 1 a ods. 2 písm. k) zákona č. 297/2008 Z. z.'),
  documents: why('Existujúce podklady použijeme na analýzu medzier doterajšieho systému a zachovanie jeho použiteľných častí.','§ 20 ods. 1 a 2; § 20a zákona č. 297/2008 Z. z.')
};

const sections: Section[] = [
  { title: 'O spoločnosti', intro: '', fields: [
    {id:'company',label:'Obchodné meno / meno SZČO',required:true,why:WHY.identity},{id:'ico',label:'IČO',required:true,why:WHY.identity},{id:'legalForm',label:'Právna forma',type:'select',options:['SZČO','s. r. o.','a. s.','Iná'],required:true,why:WHY.identity},{id:'address',label:'Sídlo',required:true,why:WHY.identity},{id:'statutory',label:'Štatutárny orgán',required:true},{id:'companyEmail',label:'E-mail spoločnosti',type:'email',required:true},{id:'companyPhone',label:'Telefón spoločnosti',type:'tel'},{id:'contactName',label:'Kontaktná osoba pre dotazník',required:true},{id:'contactEmail',label:'E-mail kontaktnej osoby',type:'email',required:true},{id:'contactPhone',label:'Telefón kontaktnej osoby',type:'tel'} ]},
  { title: 'Služby a klienti', intro: 'Rozsah činností určuje, aké situácie a riziká musí dokumentácia pokrývať.', fields: [
    {id:'services',label:'Aké služby poskytujete?',type:'checkboxes',options:['Jednoduché účtovníctvo','Podvojné účtovníctvo','Daňová evidencia','Mzdy a personalistika','DPH a daňové priznania','Účtovné závierky','Ekonomické alebo účtovné poradenstvo','Zakladanie a zmeny spoločností','Prevody obchodných podielov','Platobné príkazy alebo prístup k účtom klientov','Práca s hotovosťou','Iné'],required:true,why:WHY.services},{id:'clientCount',label:'Približný počet aktívnych klientov',type:'number',required:true,why:WHY.clientCount},{id:'industries',label:'V akých odvetviach pôsobia vaši klienti?',type:'checkboxes',options:['Obchod','Stavebníctvo','Doprava a logistika','Gastro a hotely','IT a marketing','Zdravotníctvo','Nehnuteľnosti a development','Finančné služby','Kryptomeny','Hazard','Automotive','Poľnohospodárstvo','Výroba','Import / export','Iné'],why:WHY.industries},{id:'foreignLinks',label:'Majú klienti zahraničné väzby?',type:'radio',options:['Áno','Nie','Neviem'],required:true,why:WHY.foreign},{id:'foreignDetails',label:'Uveďte krajiny a typ väzby',type:'textarea',show:a=>a.foreignLinks==='Áno',why:WHY.foreign} ]},
  { title: 'Organizácia a zodpovednosť', intro: 'Potrebujeme vedieť, kto vykonáva jednotlivé úlohy a komu majú byť pridelené povinnosti.', fields: [
    {id:'employees',label:'Počet zamestnancov',type:'number',required:true,why:WHY.organization},{id:'external',label:'Počet externých spolupracovníkov',type:'number',why:WHY.organization},{id:'clientAcceptance',label:'Kto prijíma nových klientov?',type:'checkboxes',options:['Štatutár','Zamestnanci','Externý spolupracovník','Iná osoba'],required:true,why:WHY.organization},{id:'branches',label:'Máte pobočky alebo ďalšie prevádzky?',type:'radio',options:['Áno','Nie'],required:true,why:WHY.branches},{id:'branchDetails',label:'Uveďte pobočky a osoby, ktoré v nich prijímajú klientov',type:'textarea',show:a=>a.branches==='Áno',why:WHY.branches},{id:'amlPersons',label:'Koľko osôb vykonáva alebo bude vykonávať AML úlohy?',type:'number',required:true,why:WHY.organization} ]},
  { title: 'Doterajšie AML procesy', intro: 'Detailné otázky sa zobrazia iba vtedy, ak ste AML procesy mali alebo ich používate.', fields: [
    {id:'amlHistory',label:'Máte alebo ste v minulosti mali zavedené AML procesy?',type:'radio',options:['Nie, nemáme ani sme nemali','Áno, používame ich','Čiastočne alebo sme ich mali v minulosti'],required:true,why:WHY.existing},
    {id:'identityMethod',label:'Ako ste overovali totožnosť klienta?',type:'textarea',show:a=>a.amlHistory!=='Nie, nemáme ani sme nemali'&&!!a.amlHistory,why:WHY.identityMethod},{id:'beneficialOwner',label:'Ako ste zisťovali a overovali konečného užívateľa výhod?',type:'textarea',show:a=>a.amlHistory!=='Nie, nemáme ani sme nemali'&&!!a.amlHistory,why:WHY.kuv},{id:'pepSanctions',label:'Ako ste kontrolovali PEP a sankčné zoznamy?',type:'textarea',show:a=>a.amlHistory!=='Nie, nemáme ani sme nemali'&&!!a.amlHistory,why:WHY.pepSanctions},{id:'riskAssignment',label:'Prideľovali ste klientom rizikovú kategóriu?',type:'radio',options:['Áno','Nie','Čiastočne'],show:a=>a.amlHistory!=='Nie, nemáme ani sme nemali'&&!!a.amlHistory,why:WHY.risk},{id:'monitoring',label:'Ako ste aktualizovali údaje a sledovali neobvyklé operácie?',type:'textarea',show:a=>a.amlHistory!=='Nie, nemáme ani sme nemali'&&!!a.amlHistory,why:WHY.monitoring} ]},
  { title: 'Prijatie klienta a overovanie', intro: 'Odpovede použijeme na nastavenie praktického postupu od prvého kontaktu s klientom.', fields: [
    {id:'onboarding',label:'Ako najčastejšie prijímate klientov?',type:'radio',options:['Osobne','Na diaľku','Kombinovane'],required:true,why:WHY.onboarding},{id:'remoteProcess',label:'Opíšte prijatie a overenie klienta na diaľku',type:'textarea',show:a=>a.onboarding==='Na diaľku'||a.onboarding==='Kombinovane',why:WHY.onboarding},{id:'requestedDocs',label:'Aké doklady a informácie od klienta žiadate?',type:'textarea',required:true,why:WHY.identityMethod},{id:'writtenContract',label:'Máte s klientmi písomnú zmluvu?',type:'radio',options:['Áno, vždy','Nie vždy','Nie'],required:true},{id:'purposeKnown',label:'Poznáte účel spolupráce a podnikanie klienta?',type:'radio',options:['Áno, vždy','Väčšinou','Nie vždy','Nie'],required:true,why:WHY.purpose},{id:'refusedClient',label:'Odmietli alebo ukončili ste spoluprácu pre podozrivé okolnosti?',type:'radio',options:['Áno','Nie'],required:true,why:WHY.refusal},{id:'refusedDetails',label:'Bez osobných údajov klienta stručne opíšte situáciu a postup',type:'textarea',show:a=>a.refusedClient==='Áno',why:WHY.refusal} ]},
  { title: 'Riziká a neobvyklé operácie', intro: 'Pomôže nám to vytvoriť rizikový profil zodpovedajúci reálnej klientele kancelárie.', fields: [
    {id:'complexOwnership',label:'Stretávate sa s komplikovaným vlastníctvom, trustmi alebo nejasným KÚV?',type:'radio',options:['Áno','Nie','Neviem'],required:true,why:WHY.ownership},{id:'knownPep',label:'Máte alebo ste mali klienta, ktorý je politicky exponovanou osobou (PEP)?',type:'radio',options:['Áno','Nie','Nie som si istý/á'],required:true,why:WHY.pepSanctions},{id:'sanctions',label:'Zistili ste niekedy väzbu klienta na sankčnú osobu alebo krajinu?',type:'radio',options:['Áno','Nie','Nie som si istý/á'],required:true,why:WHY.pepSanctions},{id:'riskSituations',label:'S akými situáciami sa stretávate?',type:'checkboxes',options:['Platby tretích osôb','Transakcie bez zrejmého ekonomického dôvodu','Pôžičky medzi prepojenými osobami','Neobvyklé zálohy alebo dobropisy','Vysoký obrat pri minimálnej činnosti','Hotovostné operácie','Neobvyklé zahraničné platby','Zložité vlastnícke štruktúry','Operácie nezodpovedajúce profilu klienta','So žiadnou z uvedených'],why:WHY.situations},{id:'crypto',label:'Máte klientov, ktorí používajú kryptomeny?',type:'radio',options:['Áno','Nie','Neviem'],why:WHY.crypto},{id:'cashDetails',label:'V ktorých odvetviach a v akom rozsahu sa stretávate s hotovosťou?',type:'textarea',why:WHY.cash} ]},
  { title: 'Hlásenia, účty a hotovosť', intro: 'Tieto odpovede spresnia kontrolné mechanizmy a postup pri neobvyklej obchodnej operácii.', fields: [
    {id:'suspicious',label:'Riešili ste už podozrivú transakciu alebo správanie klienta?',type:'radio',options:['Áno','Nie'],required:true,why:WHY.suspicious},{id:'suspiciousDetails',label:'Bez identifikačných údajov klienta opíšte typ situácie a váš postup',type:'textarea',show:a=>a.suspicious==='Áno',why:WHY.suspicious},{id:'goaml',label:'Ste registrovaní v systéme goAML?',type:'radio',options:['Áno','Nie','Registrácia prebieha','Neviem'],required:true,why:WHY.goaml},{id:'bankAccess',label:'Aký prístup máte k bankovým účtom klientov?',type:'checkboxes',options:['Žiadny','Iba náhľad','Príprava platieb','Autorizácia platieb'],why:WHY.payments},{id:'paymentApproval',label:'Ako sa platby pripravujú a schvaľujú?',type:'textarea',show:a=>Array.isArray(a.bankAccess)&&a.bankAccess.some(x=>x!=='Žiadny'),why:WHY.payments},{id:'clientCash',label:'Preberáte alebo uschovávate hotovosť klientov?',type:'radio',options:['Áno','Nie'],why:WHY.cash},{id:'clientCashDetails',label:'Opíšte spôsob práce s hotovosťou',type:'textarea',show:a=>a.clientCash==='Áno',why:WHY.cash} ]},
  { title: 'Zodpovedná osoba, systémy a dokumenty', intro: 'Na záver nastavíme zodpovednosť, uchovávanie záznamov a zohľadníme existujúce podklady.', fields: [
    {id:'responsibleName',label:'Meno a priezvisko navrhovanej zodpovednej osoby',required:true,why:WHY.amlPerson},{id:'responsibleRole',label:'Pracovná pozícia / funkcia',required:true,why:WHY.amlPerson},{id:'responsibleEmail',label:'E-mail',type:'email',required:true},{id:'responsiblePhone',label:'Telefón',type:'tel'},{id:'statutoryMember',label:'Je táto osoba členom štatutárneho orgánu?',type:'radio',options:['Áno','Nie'],required:true,why:WHY.amlPerson},{id:'deputy',label:'Má mať zodpovedná osoba interného zástupcu?',type:'radio',options:['Áno','Nie','Potrebujeme odporúčanie'],why:WHY.amlPerson},{id:'systems',label:'Aké účtovné a klientské systémy používate?',type:'textarea',required:true,why:WHY.systems},{id:'storage',label:'Ako uchovávate dokumenty a záznamy?',type:'checkboxes',options:['Papierovo','Lokálny počítač alebo server','Cloudové úložisko','Dokumentový systém','Účtovný systém','Kombinácia','Inak'],required:true,why:WHY.systems},{id:'inspection',label:'Absolvovali ste už AML kontrolu?',type:'radio',options:['Áno','Nie'],why:WHY.inspection},{id:'inspectionDetails',label:'Uveďte zistenia a prijaté opatrenia',type:'textarea',show:a=>a.inspection==='Áno',why:WHY.inspection},{id:'existingDocs',label:'Aké podklady už máte?',type:'checkboxes',options:['Existujúci AML program','Hodnotenie rizík','KYC / AML formuláre','Interné postupy','Záznamy zo školení','Správa z kontroly','Organizačná schéma','Vzor zmluvy s klientom','Nemáme žiadne'],why:WHY.documents},{id:'additional',label:'Ďalšie špecifiká alebo požiadavky',type:'textarea'} ]}
];

const Why = ({text}:{text?:string}) => { if(!text)return null; const [reason,legal]=text.split('\n\nPrávny základ: '); return <details className="mt-3 rounded-xl border border-teal-100 bg-teal-50/50 p-3 text-sm text-slate-600"><summary className="cursor-pointer inline-flex items-center gap-1.5 text-[#087f8c] font-bold"><HelpCircle size={15}/>Prečo je údaj potrebný?</summary><p className="mt-3 leading-6">{reason}</p>{legal&&<p className="mt-3 pt-3 border-t border-teal-100 text-xs leading-5"><strong>Právny základ:</strong> {legal}</p>}</details> };

export default function AMLQuestionnaireView(){
  const [step,setStep]=useState(0); const [a,setA]=useState<Answers>({}); const [sending,setSending]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState(''); const [started]=useState(Date.now());
  const visible=useMemo(()=>sections[step].fields.filter(f=>!f.show||f.show(a)),[step,a]);
  const set=(id:string,v:string|boolean|string[])=>setA(x=>({...x,[id]:v}));
  const missing=visible.some(f=>f.required && (!a[f.id]||(Array.isArray(a[f.id])&&(a[f.id] as string[]).length===0)));
  const submit=async()=>{ setSending(true);setError(''); try{const r=await fetch('/api/aml-questionnaire',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({answers:a,privacyAccepted:a.privacy===true,confirmation:a.confirmation===true,website:'',formStartedAt:started})});const contentType=r.headers.get('content-type')||'';if(!contentType.includes('application/json'))throw new Error('Server formulára nie je dostupný. Skúste stránku obnoviť alebo to zopakujte po nasadení najnovšej verzie webu.');const j=await r.json();if(!r.ok)throw new Error(j.error||'Dotazník sa nepodarilo odoslať.');setDone(true);window.scrollTo({top:0,behavior:'smooth'});}catch(e:any){setError(e.message||'Dotazník sa nepodarilo odoslať. Skontrolujte pripojenie a skúste to znova.')}finally{setSending(false)}};
  if(done)return <main className="min-h-screen bg-[#f4f8fb] grid place-items-center p-6"><div className="max-w-xl bg-white rounded-3xl p-10 shadow-xl text-center"><CheckCircle2 className="mx-auto text-emerald-500" size={64}/><h1 className="text-3xl font-black text-[#002b4e] mt-5">Dotazník bol odoslaný</h1><p className="text-slate-600 mt-3">Ďakujeme. Odpovede sme doručili spracovateľovi AML dokumentácie.</p></div></main>;
  return <main className="min-h-screen bg-[#f4f8fb] text-slate-800"><header className="relative overflow-hidden bg-gradient-to-r from-[#002b4e] via-[#064968] to-[#087f8c] text-white"><div className="absolute -right-16 -top-24 h-56 w-56 rounded-full bg-orange-400/15 blur-3xl"/><div className="absolute left-1/3 -bottom-20 h-40 w-40 rounded-full bg-cyan-300/10 blur-3xl"/><div className="relative max-w-5xl mx-auto px-5 py-6 md:py-7"><h1 className="flex flex-wrap items-baseline gap-x-3 gap-y-0.5 text-2xl md:text-3xl font-black"><span>AML dotazník</span><span className="text-base md:text-lg font-semibold text-orange-300">pre účtovnú kanceláriu</span></h1><p className="text-white/75 mt-2 max-w-4xl text-sm md:text-base leading-relaxed">Odpovede slúžia na prípravu individualizovanej AML dokumentácie podľa § 20 zákona č. 297/2008&nbsp;Z.&nbsp;z.</p></div></header>
  <div className="max-w-5xl mx-auto px-5 py-8"><div className="flex justify-between text-sm font-semibold text-slate-500 mb-2"><span>Krok {step+1} z {sections.length}</span><span>{Math.round((step+1)/sections.length*100)} %</span></div><div className="h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-orange-500 transition-all" style={{width:`${(step+1)/sections.length*100}%`}}/></div>
  <section className="bg-white rounded-3xl shadow-lg border border-slate-100 p-6 md:p-10 mt-6"><div className="flex gap-4"><div className="w-12 h-12 rounded-2xl bg-orange-100 text-orange-500 grid place-items-center shrink-0"><FileCheck2/></div><div><h2 className="text-2xl font-black text-[#002b4e]">{sections[step].title}</h2>{sections[step].intro&&<p className="text-slate-500 mt-1">{sections[step].intro}</p>}</div></div><div className="grid md:grid-cols-2 gap-6 mt-8">{visible.map(f=><div key={f.id} className={f.type==='textarea'||f.type==='checkboxes'||f.type==='radio'?'md:col-span-2':''}><label className="font-bold text-[#123b59]">{f.label}{f.required&&<span className="text-orange-500"> *</span>}</label>{f.type==='textarea'?<textarea value={(a[f.id] as string)||''} onChange={e=>set(f.id,e.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-slate-300 p-3 focus:ring-2 focus:ring-orange-400 outline-none"/>:f.type==='select'?<select value={(a[f.id] as string)||''} onChange={e=>set(f.id,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3"><option value="">Vyberte...</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==='radio'?<div className="flex flex-wrap gap-3 mt-3">{f.options?.map(o=><label key={o} className={`px-4 py-2 rounded-xl border cursor-pointer ${a[f.id]===o?'border-orange-500 bg-orange-50':'border-slate-200'}`}><input className="mr-2" type="radio" name={f.id} checked={a[f.id]===o} onChange={()=>set(f.id,o)}/>{o}</label>)}</div>:f.type==='checkboxes'?<div className="grid sm:grid-cols-2 gap-2 mt-3">{f.options?.map(o=>{const vals=(a[f.id] as string[])||[];return <label key={o} className="p-3 rounded-xl border border-slate-200"><input className="mr-2 accent-orange-500" type="checkbox" checked={vals.includes(o)} onChange={()=>set(f.id,vals.includes(o)?vals.filter(x=>x!==o):[...vals,o])}/>{o}</label>})}</div>:<input type={f.type||'text'} value={(a[f.id] as string)||''} onChange={e=>set(f.id,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3 focus:ring-2 focus:ring-orange-400 outline-none"/>}<Why text={f.why}/></div>)}</div>
  {step===sections.length-1&&<div className="mt-8 border-t pt-6 space-y-4"><label className="flex gap-3"><input type="checkbox" checked={a.confirmation===true} onChange={e=>set('confirmation',e.target.checked)} className="mt-1 accent-orange-500"/><span>Potvrdzujem, že uvedené údaje sú podľa môjho vedomia aktuálne a pravdivé.</span></label><label className="flex gap-3"><input type="checkbox" checked={a.privacy===true} onChange={e=>set('privacy',e.target.checked)} className="mt-1 accent-orange-500"/><span>Oboznámil/a som sa so <a href="/gdpr" target="_blank" className="text-[#087f8c] underline">Zásadami ochrany osobných údajov</a>.</span></label></div>}{error&&<p className="mt-5 p-3 bg-red-50 text-red-700 rounded-xl">{error}</p>}
  <div className="flex justify-between mt-9"><button disabled={step===0} onClick={()=>{setStep(s=>s-1);window.scrollTo(0,0)}} className="px-5 py-3 font-bold disabled:opacity-30 flex gap-2"><ChevronLeft/>Späť</button>{step<sections.length-1?<button disabled={missing} onClick={()=>{setStep(s=>s+1);window.scrollTo(0,0)}} className="px-6 py-3 bg-[#002b4e] text-white rounded-xl font-bold disabled:opacity-40 flex gap-2">Pokračovať<ChevronRight/></button>:<button disabled={missing||a.confirmation!==true||a.privacy!==true||sending} onClick={submit} className="px-6 py-3 bg-orange-500 text-white rounded-xl font-bold disabled:opacity-40 flex gap-2">{sending?<Loader2 className="animate-spin"/>:<Send/>}Odoslať dotazník</button>}</div></section></div></main>
}
